personsname= input('Enter a person\'s name: ')
noun= input('Enter a noun: ')
adjective= input('Enter a feeling (eg. moody, angry, happy, etc.): ')
verb= input('Enter a verb: ')
adjectivefeeling= input('Enter a feeling: ')
animal= input('Enter a/an animal: ')
verbs= input('Enter a verb: ')
color= input('Enter a color: ')
secondverb= input('Enter a verb ending with \'ing\': ')
adverb= input('Enter an adverb ending with \'ly\': ')
number= input('Enter a number: ')
measureoftime= input('Enter a measure of time (eg. days, weeks, months, years, decades, fortnights, centuries, etc.): ')
color= input('Enter a color: ')
animals= input('Enter an animal: ')
number= input('Enter a number: ')
sillyword= input('Enter a sillyword: ')
nounn= input('Enter a noun: ')

print('This weekend, I am going camping with ' + personsname + '.')
print('I packed my lantern, sleeping bag, and ' + noun + '.')
print('I am so ' + adjective +' to ' + verb + ' in a tent.')
print('I am ' + adjectivefeeling + ' we might see a/an ' + animal + ', they are kind of dangerous.' )
print('We are are going to hike, fish, and ' + verbs + '.')
print('I have heard that the ' + color + ' lake is great for ' + secondverb + '.')
print('Then we will ' + adverb + ' hike through the forest for ' + number + ' ' + measureoftime + '.')
print('If i see a ' + color + ' ' + animals + ' while hiking, I am going to bring it home as a pet!')
print('At night, we will tell ' + number + ' ' + sillyword + ' stories and roast ' + nounn + ' around the campfire!!!')

